//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EUFA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchEvents = new HashSet<MatchEvent>();
            this.MatchParticipations = new HashSet<MatchParticipation>();
        }
    
        public int Id { get; set; }
        public string StageCode { get; set; }
        public int TeamA { get; set; }
        public int TeamB { get; set; }
    
        public virtual TournamentParticipation TournamentParticipation { get; set; }
        public virtual TournamentParticipation TournamentParticipation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchEvent> MatchEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchParticipation> MatchParticipations { get; set; }
    }
}
